services:
  app:
    image: ${PROJECT_NAME}:${IMAGE_VERSION}
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
        USERNAME: ${USERNAME}
        GROUPNAME: ${GROUPNAME}
        WORKDIR: ${WORKDIR}
        NODE_IMAGE_TAG: ${NODE_IMAGE_TAG}
    tty: true
    environment:
        - TZ:${TIMEZONE}
    volumes:
      - .:${WORKDIR}
